version: '3'
services:
  # Conteneur pour la base de données de MySQL
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - "3306:3306"
    volumes:
     - ./sql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=memory
  # Container pour le serveur web sous apache avec php7
  site:
    build: .
    restart: always
    ports :
     - "80:80"
    volumes:
     - /chemin/vers/app/memory/www:/var/www/html/
    links:
     - db
  # Container pour phpmyadmin (facultatif pour faire fonctionner l'application)
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     restart: always
     depends_on:
      - db
     ports :
      - "8080:80"
     links:
      - db:mysql